### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by paulodbs21** [p1mpus/ltddos#2]
gives error 

Traceback (most recent call last):
  File "<string>", line 12, in <module>
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LTDDoS_run.py", line 20, in <module>
    ____("".join(chr(int(OO00O0OO00O0O0OO00 / 2)) for OO00O0OO00O0O0OO00 in [202, 240, 202, 198] if _____ != ______))(
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 23, in <module>
  File "<string>", line 226, in <module>
  File "pyobfuscate.com", line 1, in <module>
TypeError: expected some sort of slice, but got <_ast.Constant object at 0x7fafebe0a9d0>

**Comment by ken3009le** [comment]
The Obf broke the whole project
